services:
  server1:
    build: ./server1
    ports:
      - "3001:3001"
  server2:
    build: ./server2
    ports:
      - "3002:3002"
  server3:
    build: ./server3
    ports:
      - "3003:3003"
  aggregator:
    build: ./aggregator
    ports:
      - "4000:4000"
    depends_on:
      - server1
      - server2
      - server3